stages:
  - build
  - deploy

before_script:
  - if [ "$CI_COMMIT_REF_NAME" = "master" ] ; then ENVIRONMENT=PROD ; else ENVIRONMENT=DEV ; fi

build:
  stage: build
  script:
    - pipeline-scripts/setDynamoDbTableName.sh $ENVIRONMENT
    - gradle --stop
    - echo "*** $(date +%T) Building Trivia Royale ***"
    - gradle clean buildZip

    - echo "*** $(date +%T) Uploading deployment package to S3 ***"
    - pipeline-scripts/upload.sh $ENVIRONMENT

    - echo "*** $(date +%T) Build successful! ***"

  artifacts:
    paths:
      - build/reports/*
      - build/distributions/*.zip
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - echo "*** $(date +%T) Deploying Lambda Function ***"
    - pipeline-scripts/deploy.sh $ENVIRONMENT

    - echo "*** $(date +%T) Deployment successful! ***"

  when: manual

