stages:
  - test
  - build

codenarc:
  stage: test
  script:
    - gradle check

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always

  artifacts:
    paths:
      - build/reports/codenarc/*.html
    expire_in: 1 week
    when: always

build:
  stage: build
  script:
    - gradle clean buildZip

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success

  artifacts:
    paths:
      - build/distributions/trivia-royale.zip
    expire_in: 1 week
