stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle --stop
    - echo "*** $(date +%T) Building Trivia Royale ***"
    - gradle clean buildZip

    - echo "*** $(date +%T) Uploading deployment package to S3 ***"
    - pipeline-scripts/upload.sh

    - echo "*** $(date +%T) Build successful! ***"

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success

  artifacts:
    paths:
      - build/reports/*
      - build/distributions/*.zip
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - echo "*** $(date +%T) Deploying Lambda Function ***"
    - pipeline-scripts/deploy.sh

    - echo "*** $(date +%T) Deployment successful! ***"

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: manual
