variables:
  S3_DEPLOY_BUCKET: s3://trivaroyale-deploy

stages:
  - test
  - build

codenarc and tests:
  stage: test
  script:
    - gradle check

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always

  artifacts:
    paths:
      - build/reports/*
    expire_in: 1 week
    when: always

build:
  stage: build
  script:
    - echo "*** $(date +%T) Building Trivia Royale ***"
    - gradle clean buildZip
    - DEPLOY_PACKAGE_NAME=trivia-royale-$(date +%m%d%Y_%H%M%S).zip

    - mv build/distributions/trivia-royale.zip ./$DEPLOY_PACKAGE_NAME

    - echo "*** $(date +%T) Uploading deployment package to S3 ***"
    - aws s3 cp $DEPLOY_PACKAGE_NAME $S3_DEPLOY_BUCKET/$DEPLOY_PACKAGE_NAME

    - echo "*** $(date +%T) Build successful! ***"

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success

  artifacts:
    paths:
      - ./*.zip
    expire_in: 1 week
