stages:
  - test
  - build

codenarc:
  stage: test
  script:
    - gradle check

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always

  artifacts:
    paths:
      - build/reports/codenarc/main.html
    expire_in: 1 week

build:
  stage: build
  script:
    - gradle clean buildZip

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always

  artifacts:
    paths:
      - build/distributions/trivia-royale.zip
    expire_in: 1 week
