stages:
  - build

build:
  stage: build
  script:
    - gradle clean buildZip

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always

  artifacts:
    paths:
      - build/distributions/trivia-royale.zip
    expose_as: trivia-royale.zip
    expire_in: 1 week
